package pitslify.api.enums;

public enum MensagemRetorno {
    FALHA_AO_DELETAR,
    FALHA_AO_EDITAR,
    FALHA_AO_ADICIONAR,
    FALHA_AO_LISTAR,
    ITEM_NAO_EXISTE,
    ADICIONADO_COM_SUCESSO,
    EXCLUIDO_COM_SUCESSO,
    EDITADO_COM_SUCESSO,

}
